defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: ericmilford_development

test:
  <<: *defaults
  database: ericmilford_test

production:
  <<: *defaults
  database: ericmilford
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
